include_guard(GLOBAL)

# Authoritative configure-time contract for the only model accepted by
# StemgenRT. Replacing the qualified graph starts here: CMake artifact checks,
# Apple bundle sealing, the generated C++ contract, runtime validation, and
# native tests all consume these values.
set(STEMGENRT_QUALIFIED_CONTRACT_ID
    "c126-step100k-current-chunk-unqualified-listening")

set(STEMGENRT_QUALIFIED_MODEL_SHA256
    "afe49a4512ddadb1ef6259c7b9ab9e1aec5287734cdec944bc05af9b0c30bf8c")
set(STEMGENRT_QUALIFIED_MODEL_BYTE_SIZE 127151108)
set(STEMGENRT_QUALIFIED_CHECKPOINT_SHA256
    "4b64ef3f9c16c2c8cb0a7e255b2c524c8f4a4392354e9735068236ac0ffe64a4")

set(STEMGENRT_QUALIFIED_SAMPLE_RATE 44100)
set(STEMGENRT_QUALIFIED_CHANNELS 2)
set(STEMGENRT_QUALIFIED_STEMS 4)
set(STEMGENRT_QUALIFIED_HOP_SAMPLES 512)
set(STEMGENRT_QUALIFIED_ANALYSIS_WINDOW_SAMPLES 1024)
set(STEMGENRT_QUALIFIED_FUSION_HIDDEN_LAYERS 2)
set(STEMGENRT_QUALIFIED_FUSION_HIDDEN_SIZE 1000)
set(STEMGENRT_QUALIFIED_MODEL_OUTPUT_DELAY_CHUNKS 0)

set(STEMGENRT_QUALIFIED_INPUT_AUDIO_NAME "audio_chunk")
set(STEMGENRT_QUALIFIED_INPUT_PAST_NAME "past_audio")
set(STEMGENRT_QUALIFIED_INPUT_HIDDEN_NAME "fusion_hidden")
set(STEMGENRT_QUALIFIED_OUTPUT_SEPARATED_NAME "separated_chunk")
set(STEMGENRT_QUALIFIED_OUTPUT_PAST_NAME "next_past_audio")
set(STEMGENRT_QUALIFIED_OUTPUT_HIDDEN_NAME "next_fusion_hidden")
set(STEMGENRT_QUALIFIED_METADATA_INPUT_NAMES
    "[\"${STEMGENRT_QUALIFIED_INPUT_AUDIO_NAME}\",\"${STEMGENRT_QUALIFIED_INPUT_PAST_NAME}\",\"${STEMGENRT_QUALIFIED_INPUT_HIDDEN_NAME}\"]")
set(STEMGENRT_QUALIFIED_METADATA_OUTPUT_NAMES
    "[\"${STEMGENRT_QUALIFIED_OUTPUT_SEPARATED_NAME}\",\"${STEMGENRT_QUALIFIED_OUTPUT_PAST_NAME}\",\"${STEMGENRT_QUALIFIED_OUTPUT_HIDDEN_NAME}\"]")

# C++ initializer spelling for each exact static tensor shape. Derive repeated
# axes from the scalar contract values so changing a future qualified hop or
# state dimension cannot leave a stale shape literal behind.
set(STEMGENRT_QUALIFIED_INPUT_AUDIO_SHAPE
    "1, ${STEMGENRT_QUALIFIED_CHANNELS}, ${STEMGENRT_QUALIFIED_HOP_SAMPLES}")
set(STEMGENRT_QUALIFIED_INPUT_PAST_SHAPE
    "${STEMGENRT_QUALIFIED_INPUT_AUDIO_SHAPE}")
set(STEMGENRT_QUALIFIED_INPUT_HIDDEN_SHAPE
    "${STEMGENRT_QUALIFIED_FUSION_HIDDEN_LAYERS}, 1, ${STEMGENRT_QUALIFIED_FUSION_HIDDEN_SIZE}")
set(STEMGENRT_QUALIFIED_OUTPUT_SEPARATED_SHAPE
    "1, ${STEMGENRT_QUALIFIED_STEMS}, ${STEMGENRT_QUALIFIED_CHANNELS}, ${STEMGENRT_QUALIFIED_HOP_SAMPLES}")
set(STEMGENRT_QUALIFIED_OUTPUT_PAST_SHAPE
    "${STEMGENRT_QUALIFIED_INPUT_AUDIO_SHAPE}")
set(STEMGENRT_QUALIFIED_OUTPUT_HIDDEN_SHAPE
    "${STEMGENRT_QUALIFIED_INPUT_HIDDEN_SHAPE}")

set(STEMGENRT_QUALIFIED_METADATA_EXPORT_MODE "streaming")
set(STEMGENRT_QUALIFIED_METADATA_MIXTURE_CONSISTENCY "route_residual")
set(STEMGENRT_QUALIFIED_DRUMS_SOURCE_INDEX 0)
set(STEMGENRT_QUALIFIED_BASS_SOURCE_INDEX 1)
set(STEMGENRT_QUALIFIED_VOCALS_SOURCE_INDEX 2)
set(STEMGENRT_QUALIFIED_OTHER_SOURCE_INDEX 3)
set(STEMGENRT_QUALIFIED_RESIDUAL_SOURCE_INDEX
    "${STEMGENRT_QUALIFIED_OTHER_SOURCE_INDEX}")
set(STEMGENRT_QUALIFIED_METADATA_EXTERNAL_DATA "false")
set(STEMGENRT_QUALIFIED_METADATA_EXPORT_EXTERNAL_DATA "false")
set(STEMGENRT_QUALIFIED_METADATA_CAUSAL_CURRENT_CHUNK "true")
set(STEMGENRT_QUALIFIED_METADATA_SOURCE_ORDER
    "[\"drums\",\"bass\",\"vocals\",\"other\"]")
set(STEMGENRT_QUALIFIED_METADATA_RESIDUAL_SOURCE_NAME "other")
set(STEMGENRT_QUALIFIED_METADATA_EXTERNAL_OVERLAP_ADD "false")
set(STEMGENRT_QUALIFIED_METADATA_FUSION_HIDDEN_SHAPE
    "[${STEMGENRT_QUALIFIED_FUSION_HIDDEN_LAYERS},1,${STEMGENRT_QUALIFIED_FUSION_HIDDEN_SIZE}]")
# c126 has no boundary overlap tensor. The exporter records that fact as an
# intentionally present metadata key with an empty value.
set(STEMGENRT_QUALIFIED_METADATA_OVERLAP_ADD_BUFFER_SHAPE "")
set(STEMGENRT_QUALIFIED_METADATA_INITIAL_STATE "all_zeros")
set(STEMGENRT_QUALIFIED_METADATA_PREROLL "none")
set(STEMGENRT_QUALIFIED_METADATA_FLUSH "none")
set(STEMGENRT_QUALIFIED_METADATA_RESET
    "zero_past_audio_and_fusion_hidden")
set(STEMGENRT_QUALIFIED_METADATA_DEPLOYMENT_STATUS
    "unqualified_listening_only")
set(STEMGENRT_QUALIFIED_METADATA_QUALITY_GUARDS "37_pass_3_fail")
set(STEMGENRT_QUALIFIED_OUTPUT_ALIGNMENT "current_input_chunk")
