include_guard(GLOBAL)

# Authoritative configure-time contract for the unpromoted c214 step-100000
# listening candidate. This branch intentionally remains separate from the
# qualified 512-hop fallback until target-Mac timing and listening approval.
set(STEMGENRT_QUALIFIED_CONTRACT_ID
    "c214-step100000-hop256-c191-listening-v1")

set(STEMGENRT_QUALIFIED_MODEL_SHA256
    "8262f56503f1f8acf2cdb105822db474de2ec546b5f9dd0521bdc6b06b3a02ab")
set(STEMGENRT_QUALIFIED_MODEL_BYTE_SIZE 111372674)
set(STEMGENRT_QUALIFIED_C214_CHECKPOINT_SHA256
    "a348fede94871af5255f8bb945cd0643cc2d7694bf41e7ab78456fe5924e62fa")
set(STEMGENRT_QUALIFIED_C214_CHECKPOINT_STATE_SHA256
    "3ec18db8674bd3e6e8f57f62e43999260599554b5308a2fc15874b0ac312e99d")
set(STEMGENRT_QUALIFIED_C214_MATERIALIZED_MODEL_STATE_SHA256
    "5d6d6e1346621cfa953742a1c6ebd7ff46becd23ba3df4cba2f046e9900e8982")
set(STEMGENRT_QUALIFIED_C191_PAYLOAD_SHA256
    "a80f65f1f475815181306ef6366d077ce6fa21eebd423994744b2d6e7d2f9f5b")
set(STEMGENRT_QUALIFIED_C191_HEAD_STATE_SHA256
    "238991eced221734b5e931bbc4256412dd6ed361656f2cbe4864abccedd22bcf")
set(STEMGENRT_QUALIFIED_C214_EXPORT_QUALIFICATION_SHA256
    "a07cbf17bdc7a8653339094fae43e22ce4eaa8432312328b253221ac750dda4f")
set(STEMGENRT_QUALIFIED_C214_EXPORT_SOURCE_SEAL_SHA256
    "ba96c968b58d82974b06b807f4a2f75a7f1b908ada7e151a3a4a129af1ca4449")
set(STEMGENRT_QUALIFIED_C214_EXPORTER_SHA256
    "a9dacfd414a0cc52f796f90d5f57fbf3e251bde436096b65fe48adab2f6912db")

set(STEMGENRT_QUALIFIED_SAMPLE_RATE 44100)
set(STEMGENRT_QUALIFIED_CHANNELS 2)
set(STEMGENRT_QUALIFIED_STEMS 4)
set(STEMGENRT_QUALIFIED_HOP_SAMPLES 256)
set(STEMGENRT_QUALIFIED_ANALYSIS_WINDOW_SAMPLES 1024)
set(STEMGENRT_QUALIFIED_ANALYSIS_HISTORY_SAMPLES 768)
set(STEMGENRT_QUALIFIED_FUSION_HIDDEN_LAYERS 2)
set(STEMGENRT_QUALIFIED_FUSION_HIDDEN_SIZE 1000)
set(STEMGENRT_QUALIFIED_EMITTED_DB_CHANNELS 4)
set(STEMGENRT_QUALIFIED_EMITTED_DB_HISTORY_SAMPLES 2048)
set(STEMGENRT_QUALIFIED_MODEL_OUTPUT_DELAY_CHUNKS 0)

set(STEMGENRT_QUALIFIED_INPUT_AUDIO_NAME "audio_chunk")
set(STEMGENRT_QUALIFIED_INPUT_ANALYSIS_HISTORY_NAME "analysis_history")
set(STEMGENRT_QUALIFIED_INPUT_HIDDEN_NAME "fusion_hidden")
set(STEMGENRT_QUALIFIED_INPUT_EMITTED_DB_HISTORY_NAME "emitted_db_history")
set(STEMGENRT_QUALIFIED_OUTPUT_SEPARATED_NAME "separated_chunk")
set(STEMGENRT_QUALIFIED_OUTPUT_ANALYSIS_HISTORY_NAME "next_analysis_history")
set(STEMGENRT_QUALIFIED_OUTPUT_HIDDEN_NAME "next_fusion_hidden")
set(STEMGENRT_QUALIFIED_OUTPUT_EMITTED_DB_HISTORY_NAME
    "next_emitted_db_history")

set(STEMGENRT_QUALIFIED_INPUT_AUDIO_SHAPE
    "1, ${STEMGENRT_QUALIFIED_CHANNELS}, ${STEMGENRT_QUALIFIED_HOP_SAMPLES}")
set(STEMGENRT_QUALIFIED_INPUT_ANALYSIS_HISTORY_SHAPE
    "1, ${STEMGENRT_QUALIFIED_CHANNELS}, ${STEMGENRT_QUALIFIED_ANALYSIS_HISTORY_SAMPLES}")
set(STEMGENRT_QUALIFIED_INPUT_HIDDEN_SHAPE
    "${STEMGENRT_QUALIFIED_FUSION_HIDDEN_LAYERS}, 1, ${STEMGENRT_QUALIFIED_FUSION_HIDDEN_SIZE}")
set(STEMGENRT_QUALIFIED_INPUT_EMITTED_DB_HISTORY_SHAPE
    "1, ${STEMGENRT_QUALIFIED_EMITTED_DB_CHANNELS}, ${STEMGENRT_QUALIFIED_EMITTED_DB_HISTORY_SAMPLES}")
set(STEMGENRT_QUALIFIED_OUTPUT_SEPARATED_SHAPE
    "1, ${STEMGENRT_QUALIFIED_STEMS}, ${STEMGENRT_QUALIFIED_CHANNELS}, ${STEMGENRT_QUALIFIED_HOP_SAMPLES}")
set(STEMGENRT_QUALIFIED_OUTPUT_ANALYSIS_HISTORY_SHAPE
    "${STEMGENRT_QUALIFIED_INPUT_ANALYSIS_HISTORY_SHAPE}")
set(STEMGENRT_QUALIFIED_OUTPUT_HIDDEN_SHAPE
    "${STEMGENRT_QUALIFIED_INPUT_HIDDEN_SHAPE}")
set(STEMGENRT_QUALIFIED_OUTPUT_EMITTED_DB_HISTORY_SHAPE
    "${STEMGENRT_QUALIFIED_INPUT_EMITTED_DB_HISTORY_SHAPE}")

set(STEMGENRT_QUALIFIED_METADATA_EXPORT_MODE "streaming")
set(STEMGENRT_QUALIFIED_METADATA_MIXTURE_CONSISTENCY
    "exact_float32_residual_to_other")
set(STEMGENRT_QUALIFIED_METADATA_INPUT_NAMES
    "[\"audio_chunk\",\"analysis_history\",\"fusion_hidden\",\"emitted_db_history\"]")
set(STEMGENRT_QUALIFIED_METADATA_OUTPUT_NAMES
    "[\"separated_chunk\",\"next_analysis_history\",\"next_fusion_hidden\",\"next_emitted_db_history\"]")
set(STEMGENRT_QUALIFIED_METADATA_INPUT_SHAPES
    "[[1,2,256],[1,2,768],[2,1,1000],[1,4,2048]]")
set(STEMGENRT_QUALIFIED_METADATA_OUTPUT_SHAPES
    "[[1,4,2,256],[1,2,768],[2,1,1000],[1,4,2048]]")
set(STEMGENRT_QUALIFIED_DRUMS_SOURCE_INDEX 0)
set(STEMGENRT_QUALIFIED_BASS_SOURCE_INDEX 1)
set(STEMGENRT_QUALIFIED_VOCALS_SOURCE_INDEX 2)
set(STEMGENRT_QUALIFIED_OTHER_SOURCE_INDEX 3)
set(STEMGENRT_QUALIFIED_RESIDUAL_SOURCE_INDEX
    "${STEMGENRT_QUALIFIED_OTHER_SOURCE_INDEX}")
set(STEMGENRT_QUALIFIED_METADATA_EXTERNAL_DATA "false")
set(STEMGENRT_QUALIFIED_METADATA_SOURCE_ORDER
    "[\"drums\",\"bass\",\"vocals\",\"other\"]")
set(STEMGENRT_QUALIFIED_METADATA_CAUSAL_CURRENT_CHUNK "true")
set(STEMGENRT_QUALIFIED_METADATA_EXTERNAL_OVERLAP_ADD "false")
set(STEMGENRT_QUALIFIED_OUTPUT_ALIGNMENT "current_input_chunk")
set(STEMGENRT_QUALIFIED_METADATA_FLUSH "none")
set(STEMGENRT_QUALIFIED_METADATA_INITIAL_STATE "all_positive_zero")
set(STEMGENRT_QUALIFIED_METADATA_PREROLL "none")
set(STEMGENRT_QUALIFIED_METADATA_FIRST_CALLBACK "current_input_chunk")
set(STEMGENRT_QUALIFIED_METADATA_RESET "zero_all_3_state_tensors")
set(STEMGENRT_QUALIFIED_METADATA_STATE_COUNT "3")
set(STEMGENRT_QUALIFIED_METADATA_STATE_NAMES
    "[\"analysis_history\",\"fusion_hidden\",\"emitted_db_history\"]")
set(STEMGENRT_QUALIFIED_METADATA_DEPLOYMENT_STATUS
    "post_training_export_candidate_not_plugin_qualified")
set(STEMGENRT_QUALIFIED_METADATA_QUALITY_GUARDS
    "unpromoted_target_macos_listening_and_10k_paced_required")
